### ISSUE TITLE
info command should only display address in some entry states.

### ISSUE THREAD

**Issue by roconnor-blockstream** [apoelstra/icebox#3]
When running the info command the ledger always displays the associated address on the ledger.
Instead this should only be done when the entry is in the state `EntryState::Valid`, and definitely not when it is in the state `EntryState::Unused`.

**Comment by apoelstra** [comment]
Yikes, good call!

**Comment by apoelstra** [comment]
How about `EntryState::Received` (already used)?

**Comment by roconnor-blockstream** [comment]
I don't think it is necessary to display it on `Received`.  The addresses are not supposed to be reused.
