### ISSUE TITLE
`receive` command prints trasaction hash instead of txid.

### ISSUE THREAD

**Issue by roconnor-blockstream** [apoelstra/icebox#7]
Related to https://github.com/apoelstra/icebox/pull/6, there is a bug where the `receive` command displays the hash instead of the txid when receiving segwit endowed transactions.

**Comment by roconnor-blockstream** [comment]
`info` also lists the transaction's hash in place of the txid.  This has possibly made this input unspendable by the wallet.

**Comment by apoelstra** [comment]
Fixed in 6aa4e3ab5178c4cbd587836c9f149c7dd9771e69
